DISCORD_BOT:
  #the discord bot token needed to login
  token: ""
  #the guild IDs to listen for commands
  guilds:
    - 428163245753499653
    - 785950137289539610
  #put this text in the description of a channel to mark it as
  chat_channel_marker: "|MC-chat"
  console_channel_marker: "|MC-console"
  command_channel_marker: "|MC-commands"
  #command marker mode ALLOW/DISALLOW
  command_marker_mode: "ALLOW"


MC_SERVER:
  #the one line command needed to start the Server
  startCMD: "(cd ../../Minecraft-Test-Server/1.16.5/ && java -jar server.jar --nogui)"
  #the ip of the server (will be shown in status)
  ip: "localhost"
  #the command to send the chat messages from discord to minecraft
  #%username% will be replaced by sender username
  #%color% will be replaced by sender user color
  #%message% will be replaced by the message in json ready string format
  #%messageJSON% will be replaced with a JSON string containing the already formatted message
  say_format: "execute if entity @a run tellraw @a %messageJSON%"
  #regular expression used to recognize chat messages from the server logs ( $1 capturing group should be the chat message + username, $2 should be username only )
  chat_regex:
    - "^\\[\\d+:\\d+:\\d+] \\[Server thread\\/INFO]: (<([\\w\\d_-]+)> [^\\n\\r]+)"
    - "^\\[\\d+:\\d+:\\d+] \\[Server thread\\/INFO]: (([\\w\\d-]+) (?:(?:left)|(?:joined)) the game)"
    - "^\\[\\d+:\\d+:\\d+] \\[Server thread\\/INFO]: (\\* ([\\w\\d-]+) [^\\r\\n]+)"
    - "^\\[\\d+:\\d+:\\d+] \\[Server thread\\/INFO]: (\\[([\\w\\d_-]+)] [^\\n\\r]+)"
  save_regex: "^\\[\\d+:\\d+:\\d+] \\[Server thread\\/INFO]: Saved the game"
  done_regex: "^\\[\\d+:\\d+:\\d+] \\[Server thread\\/INFO]: Done \\([\\d.]+s\\)! For help, type \"help\""
  error_regex: "^\\[\\d+:\\d+:\\d+] \\[[^/]+\\/\\w+]:.*"


BACKUP:
  #path to the server folder ( used to initiate git repository )
  server_path: "../../Minecraft-Test-Server/1.16.4/"
  #time in seconds between backups ( <0 means disabled , also needs to be at least 1.5 times the Backup_alert time )
  backup_time: 1800
  #time in seconds before a backup ( it is used to send a warning message to the players )
  backup_alert: 30
