DISCORD_BOT:
  #the discord bot token needed to log in
  TOKEN: ""
  #the prefix the bot will answer to
  PREFIX: ""
  #the channel ID where to echo the server console
  CONSOLE_CHANNEL: ''
  #the channel ID where to write and listen to chat messages
  CHAT_CHANNEL: ''
  #webhook in chat bridge channel. It sends messages with the minecraft account's username.
  chatBridgeWebHookURL: ""

MC_SERVER:
  #The one line command needed to start the Server. For each argument use an element in the list. Please note that cd doesn't work.
  #The syntax is weird because my YAML library doesn't support something sane.

  startCMD:
    - "java"
    - "-jar"
    - ""

  #The ip that the status command pings
  ip: "localhost"
  #The port for the status command
  port: "25565"

  #for chat bridge
  normalRegexes:
    - regex:
        string: "^\[\d\d:\d\d:\d\d] \[Server thread\/INFO\]: ((?:[0-9A-z_]{3,16}) (?:(?:left)|(?:joined)) the game)"
        contentGroup: 1
    - regex:
        string: "^\[\d\d:\d\d:\d\d] \[Server thread\/INFO\]: \* ([0-9A-z_]{3,16} .+)"
        contentGroup: 1

  webHookRegexes:
    - regex:
        string: "^\[\d\d:\d\d:\d\d] \[Server thread\/INFO\]: <([0-9A-z_]{3,16})> (.+)"
        prefix: ""
        nameGroup: 1
        contentGroup: 2

  #This is the regex for the printed line indicating when the server has been started.
  startRegex: '^\[\d\d:\d\d:\d\d] \[Server thread\/INFO\]: Done \(\d+.\d+s\)! For help, type "help"'


BACKUP:
  #time in seconds between backups ( 0 means disabled)
  backup_time: 0
  #time after warning before backup
  backup_alert: 30
  #Where to run server and make backups. Needs to be an initialized git repo
  gitDirectory: "server"

  #regex for detecting when the server has let go of the world files.
  gitsavereturnRegex: '^\[\d\d:\d\d:\d\d\] \[Server thread\/INFO\]: Saved the game'


#USE IDS HERE
PERMISSIONS:
  Global:
    Roles:
      - ""
    Users:
      - ""
  server:
    Roles:
      - ""
    Users: 
      - ""
  status:
    Roles:
      - ""
    Users:
      - ""
  backup:
    Roles:
      - ""
    Users:
      - ""
  chatbridge:
    Roles:
      - ""
    Users:
      - ""